
package com.employees.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://service.employees.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://service.employees.com/", className = "com.employees.service.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://service.employees.com/", className = "com.employees.service.DeleteEmployeeResponse")
    public void deleteEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.employees.service.EmployeeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://service.employees.com/", className = "com.employees.service.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://service.employees.com/", className = "com.employees.service.AddEmployeeResponse")
    public EmployeeDto addEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        EmployeeDto arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.employees.service.EmployeeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEmployees", targetNamespace = "http://service.employees.com/", className = "com.employees.service.GetAllEmployees")
    @ResponseWrapper(localName = "getAllEmployeesResponse", targetNamespace = "http://service.employees.com/", className = "com.employees.service.GetAllEmployeesResponse")
    public List<EmployeeDto> getAllEmployees();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://service.employees.com/", className = "com.employees.service.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://service.employees.com/", className = "com.employees.service.UpdateEmployeeResponse")
    public void updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        EmployeeDto arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.employees.service.EmployeeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeById", targetNamespace = "http://service.employees.com/", className = "com.employees.service.GetEmployeeById")
    @ResponseWrapper(localName = "getEmployeeByIdResponse", targetNamespace = "http://service.employees.com/", className = "com.employees.service.GetEmployeeByIdResponse")
    public EmployeeDto getEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
