
package com.employees.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeServiceService", targetNamespace = "http://service.employees.com/", wsdlLocation = "wsemployee.wsdl")
public class EmployeeServiceService
    extends Service
{

	private static final String WSDL = "wsemployee.wsdl";
	private final static URL EMPLOYEESERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException EMPLOYEESERVICESERVICE_EXCEPTION;
    private final static QName EMPLOYEESERVICESERVICE_QNAME = new QName("http://service.employees.com/", "EmployeeServiceService");

    static {
        URL url = null;
        WebServiceException ex = null;
        try {
        	url = EmployeeServiceService.class.getResource(WSDL);
        } catch (Throwable e) {
        	ex = new WebServiceException(e);
        }
        EMPLOYEESERVICESERVICE_WSDL_LOCATION = url;
        EMPLOYEESERVICESERVICE_EXCEPTION = ex;
    }

    public EmployeeServiceService() {
        super(__getWsdlLocation(), EMPLOYEESERVICESERVICE_QNAME);
    }

    public EmployeeServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEESERVICESERVICE_QNAME, features);
    }

    public EmployeeServiceService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEESERVICESERVICE_QNAME);
    }

    public EmployeeServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEESERVICESERVICE_QNAME, features);
    }

    public EmployeeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeService
     */
    @WebEndpoint(name = "EmployeeServicePort")
    public EmployeeService getEmployeeServicePort() {
        return super.getPort(new QName("http://service.employees.com/", "EmployeeServicePort"), EmployeeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeService
     */
    @WebEndpoint(name = "EmployeeServicePort")
    public EmployeeService getEmployeeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.employees.com/", "EmployeeServicePort"), EmployeeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEESERVICESERVICE_EXCEPTION!= null) {
            throw EMPLOYEESERVICESERVICE_EXCEPTION;
        }
        return EMPLOYEESERVICESERVICE_WSDL_LOCATION;
    }

}
